### ISSUE TITLE
Improve CONTRIBUTION.md file

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#1]
Help to improve the CONTRIBUTION.md file, like adding Contributing Guideline etc..

**Comment by 96RadhikaJadhav** [comment]
@Harshal0902  Can I work on it? I'm a crosswoc participant.

**Comment by Harshal0902** [comment]
@96RadhikaJadhav you can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/RMAtpWZX) for any doubts. Try to complete it within 3 days.

**Comment by 96RadhikaJadhav** [comment]
@Harshal0902 Could you please create issues under crosswoc to create PR and issue templates and assign those to me? I would like to work on it. And also there is a typo in contributing.md file at line 83 in word 'devlopment'. You can create another issue for this and assign that to me.
Or I can also create issues and work on it if you allow.

**Comment by Harshal0902** [comment]
@96RadhikaJadhav I am opening an issue for creating PR and issue templates and assigning them to you.
