### ISSUE TITLE
Add a responsive footer to the website

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#10]
Design and add a responsive footer to the website

**Comment by soumya-badkul** [comment]
Hey, @Harshal0902 I would like to work on this issue.

**Comment by Harshal0902** [comment]
Hi @soumya-badkul, the CrossWoC will start from 13th Feb, and all the PR's after the event starts will be count as s valid contribution (for prizes). So, you can work upon this issue once the Event will start.

**Comment by soumya-badkul** [comment]
okay thanks

**Comment by greenblade29** [comment]
Hey! I want to work on this issue. Can you please assign it to me?

**Comment by jainh6148** [comment]
Hi, I would like to contribute to this project. I am a front end web developer & a freelancer as well. Kindly assign me this project.

**Comment by Thiyageshkanna** [comment]
hey!! I would like to work on this project

**Comment by soumya-badkul** [comment]
> Hi @soumya-badkul, the CrossWoC will start from 13th Feb, and all the PR's after the event starts will be count as s valid contribution (for prizes). So, you can work upon this issue once the Event will start.

@Harshal0902 I can start working on this? please assign it to me

**Comment by Hritikkumar** [comment]
Hi Sir I would like to work on this issue. Please assign it to me

**Comment by Harshal0902** [comment]
@soumya-badkul you can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/yPAb7SGG). Try to complete it within 3 days and follow the CONTRIBUTION.md for making PR.
