### ISSUE TITLE
Typos on the front page

### ISSUE THREAD

**Issue by varshitha1707** [Harshal0902/Rudra#100]
## Describe the bug
Just as you click on the link, there are three options, one of them is english and there's a typo inside that option.
And more Spelling mistakes inside the code.

![image](https://user-images.githubusercontent.com/69676094/122753691-3dedbe00-d2b0-11eb-8546-daf170eafdf1.png)

## Expected behavior
1. for "Englich" to be changed to "English"
The typos to be solved and grammatical errors resolved.

## Environment (please complete the following information):
 - OS: Windows
 - Browser: chrome

## Additional context
Please assign this issue to me under LGMSOC21

**Comment by Harshal0902** [comment]
@varshitha1707 go ahead
