### ISSUE TITLE
Add the new favicon to the site

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#104]
Replace the old favicon with new designed favicon to the site.

**Comment by RituCs** [comment]
I would like to work on this issue under LGMSOC'21 participant.

**Comment by Harshal0902** [comment]
@RituCs go for it

**Comment by Srit20** [comment]
I would like to work on this issue under LGMSOC'21 participant. Please assign me @Harshal0902

**Comment by Harshal0902** [comment]
@Srit20 the issue is already assigned to other person.

**Comment by satyampgt4** [comment]
@RituCs please close this issue
