### ISSUE TITLE
Welcome Bot for Issues 

### ISSUE THREAD

**Issue by Akash20x** [Harshal0902/Rudra#107]
## Is your feature request related to a problem? Please describe.
A welcome bot for new issue created in your repository 

@Harshal0902 Please assign me this issue as a part of LGM-SOC'21.

**Comment by Harshal0902** [comment]
@Akash20x we already have a welcome bot.

**Comment by Akash20x** [comment]
> @Akash20x we already have a welcome bot.

Yes but didn't working
