### ISSUE TITLE
Font size and gap in instructions

### ISSUE THREAD

**Issue by srisatya12** [Harshal0902/Rudra#114]
## Describe the bug
I would like to change 'INSTRUCTION' font style and font size. 

![Instructions _ RUDRA - Google Chrome 30-06-2021 22_22_26_LI](https://user-images.githubusercontent.com/78905067/124001271-130f1280-d9f2-11eb-8802-3df5139bce90.jpg)
Here there is no much gap between the sentences I would like to change this too.

**Comment by Harshal0902** [comment]
@srisatya1197 go for it, and do it for both page(Police as well as Public)

**Comment by srisatya12** [comment]
@Harshal0902 Just I want to clear that I'll be inactive on github for a week(sem exams). I want to tell that if it's ok then will complete this after a week.

**Comment by Harshal0902** [comment]
ok, no problem

**Comment by ayushnau** [comment]
Hello 
I want to contribute in this here is the link #127
