### ISSUE TITLE
Alignment 

### ISSUE THREAD

**Issue by srisatya12** [Harshal0902/Rudra#115]
![Instructions _ RUDRA - Google Chrome 30-06-2021 22_26_52_LI](https://user-images.githubusercontent.com/78905067/124001693-86188900-d9f2-11eb-99d7-a70725df4842.jpg)
As it's a professional website I want to change icons into pro one .

**Comment by Harshal0902** [comment]
@srisatya1197 go for it, and do it for both page(Police as well as Public)

**Comment by srisatya12** [comment]
@Harshal0902 Sure will do it.

**Comment by srisatya12** [comment]
@Harshal0902  Just I want to clear that I'll be inactive on github for a week(sem exams). I want to tell that if it's ok then will complete this after a week.

**Comment by Harshal0902** [comment]
ok, no problem
