### ISSUE TITLE
Add Cross WOC Banner or Poster

### ISSUE THREAD

**Issue by Ayush7614** [Harshal0902/Rudra#12]
## Is your feature request related to a problem? Please describe.
Add Cross WOC Banner or Poster

## Describe the solution you'd like
Add Cross WOC to  Banner or Poster

**Comment by Harshal0902** [comment]
@Ayush7614 you can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/RMAtpWZX) for any doubts. Try to complete it within 3 days and follow the CONTRIBUTION.md for making PR.
Add the poster in README.md file
