### ISSUE TITLE
Write a Guide for Deploying the App to Digital Ocean

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#125]
- Please name it DigitalOcean.MD
- Make and place it inside the Guides/ directory of the master branch
- Add Snapshots of the process as and where required
- Add Useful Tips section for certain optimizations, bug fixing advice, and site corresponding references

**Comment by nelsonguya** [comment]
Hello. I would like to work on writing the guide for app deployment to Digital Ocean if this is still open. Also, provide more information about the app. Regards

**Comment by Harshal0902** [comment]
@nelsonkimani63 go for it

**Comment by Harshal0902** [comment]
@nelsonkimani63 you have to create a DigitalOcean.md file under Guides/ directory where you have to state:
- What is Digital Ocean
- Steps involved to deploy the static application  on Digital Ocean
- And some tips, if possible

You can use some screenshots if necessary.

**Comment by nelsonguya** [comment]
@Harshal0902 Thank you. Just to clarify, is this for general **(not a specific app)** static applications deployment on Digital Oceans!?

**Comment by Harshal0902** [comment]
The following application is static site, so it will be better if you write process involved in deploying a static site.
