### ISSUE TITLE
changing the name of react to rudra

### ISSUE THREAD

**Issue by ayushnau** [Harshal0902/Rudra#128]
In the react version still the name is React App should I chang this to RUDRA

**Comment by Harshal0902** [comment]
In public/index.html file?

**Comment by ayushnau** [comment]
yes

**Comment by Harshal0902** [comment]
@Ayush2020012016 go for it

**Comment by gargkrishna** [comment]
I want to contribute to this issue. can you assign me??

**Comment by Harshal0902** [comment]
@gargkrishna the issue is assigned to other person, so let wait till tonight, if @Ayush2020012016 didn't do any PR I will assign this issue to you.

**Comment by Harshal0902** [comment]
@gargkrishna go for it, try to submit PR till midnight

**Comment by demonking0710** [comment]
I want to contribute to this issue.Can you assign me?

**Comment by demonking0710** [comment]
its giving 403 when i am pushing.
