### ISSUE TITLE
Improve README.md file

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#2]
Help to improve the README.md file by adding the list of contributors or wherever required.

**Comment by Sloth-Panda** [comment]
would like to work on this as part of cwoc

**Comment by Harshal0902** [comment]
Hi @Sloth-Panda , the CrossWoC will start from 13th Feb, and all the PR's after the event starts will be count as s valid contribution (for prizes). So, you can work upon this issue once the Event will start.

**Comment by arbazalam01** [comment]
Can i work on this issue

**Comment by Harshal0902** [comment]
@arbazalam01 you can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/qxgsn99W). Try to complete it within 3 days and follow the CONTRIBUTION.md for making PR.
