### ISSUE TITLE
Create a PR template

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#23]
Create a PR template where person can clearly state the changes he/she made, need any change in documentation etc..

**Comment by Harshal0902** [comment]
@96RadhikaJadhav,  I have created an issue as requested. You can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/yPAb7SGG) for any doubts. Try to complete it within 3 days.

**Comment by 96RadhikaJadhav** [comment]
@Harshal0902 Can you please assign this issue to me?

**Comment by 96RadhikaJadhav** [comment]
@Harshal0902 Can you please create another issue to add code of conduct and assign that to me?

**Comment by Harshal0902** [comment]
@96RadhikaJadhav,  sorry to inform you but Code of Conduct Issue is supposed to be done by another participant, as he is busy with another issue, he will do in after that.

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav, sorry to inform you but Code of Conduct Issue is supposed to be done by another participant, as he is busy with another issue, he will do in after that.

Okay :(
