### ISSUE TITLE
Create an issue templates

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#24]
Create an issue templates, which includes weather the issue is a bug or feature request, etc.

**Comment by Harshal0902** [comment]
@96RadhikaJadhav,  I have created an issue as requested. You can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/yPAb7SGG) for any doubts. Try to complete it within 3 days.

**Comment by 96RadhikaJadhav** [comment]
@Harshal0902 Can you please assign this issue to me?
