### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [Harshal0902/Rudra#27]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Please assign it to me as a part of Cross Woc.

**Comment by Harshal0902** [comment]
@muthuannamalai12 you can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/qxgsn99W) for any doubts. Try to complete it within 3 days.

**Comment by muthuannamalai12** [comment]
@Harshal0902 For the custom message shown by the welcome bot we need a code of conduct. So for that reason I have opened a issue for code of conduct file. Kindly assign me that #30 issue.

**Comment by Harshal0902** [comment]
Hi, @muthuannamalai12 the Code of Conduct Issue is supposed to be done by another participant, as he is busy with another issue, he will do in after that. Till then you can wait, or go for other issues.

**Comment by muthuannamalai12** [comment]
> Hi, @muthuannamalai12 the Code of Conduct Issue is supposed to be done by another participant, as he is busy with another issue, he will do in after that. Till then you can wait, or go for other issues.

@Harshal0902 Ok I will wait untill they complete. Thank you for your reply

**Comment by Harshal0902** [comment]
@muthuannamalai12 I have created a issue for creation of Code of Conduct. Request there so that I can Assign that issue to you.
