### ISSUE TITLE
Connect Crime reporting page to backend.

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#3]
Connect crime reporting page in the public section to the backend.

**Comment by Abhinav0909** [comment]
Hi @Harshal0902  Please assign this issue to me.

**Comment by Harshal0902** [comment]
@Abhinav0909  you can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/qxgsn99W). Try to complete it within 3 days and follow the CONTRIBUTION.md for making PR.
