### ISSUE TITLE
Add a Preloader to the site

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#31]
Add a preloader to the site

**Comment by Abhinav0909** [comment]
Hi, @Harshal0902 I want to work on this issue.

**Comment by Harshal0902** [comment]
@Abhinav0909 you can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/qxgsn99W). Try to complete it within 3 days and follow the CONTRIBUTION.md for making PR.

**Comment by Harshal0902** [comment]
@Abhinav0909 what's the status?
Are you facing any problem?

**Comment by arushijain-20** [comment]
Hey @Harshal0902, I want to work on this issue.
