### ISSUE TITLE
associate link of the crosswoc website to its banner

### ISSUE THREAD

**Issue by yashlikescode** [Harshal0902/Rudra#38]
I will associate link of the crosswoc website to its banner such that, if someone clicks the banner on readme file, it will redirect them to the website of crosswoc.

**Comment by Harshal0902** [comment]
@kmryashasvi you can work on this issue. you are requested to join the discord server for any query using this [link](https://discord.gg/NCTnAbTg).

**Comment by yashlikescode** [comment]
now this issue can be closed after merging the above pull request?
