### ISSUE TITLE
Add chatbot to every page

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#4]
Add chatbot assistant to every page for specific section.

**Comment by Abhinav0909** [comment]
Hi, @Harshal0902  I want to work on this issue.

**Comment by Harshal0902** [comment]
@Abhinav0909 you can work on this issue.

**Comment by Harshal0902** [comment]
@Abhinav0909 what's the status?
Are you facing any problem?

**Comment by Sukriti-sood** [comment]
I want to work on this

**Comment by Harshal0902** [comment]
@Sukriti-sood go for it. Try to make a pop-up-type chatbot.
