### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by yashlikescode** [Harshal0902/Rudra#42]
like the one mentioned below
![image](https://user-images.githubusercontent.com/66861659/110196907-c5343480-7e6d-11eb-931b-6591208ca410.png)

**Comment by Harshal0902** [comment]
@kmryashasvi got for it. Also add a section for *Our valuable Contributors* and add this their photo using this link: https://contributors-img.web.app/image?repo=Harshal0902/Rudra

**Comment by yashlikescode** [comment]
I can add contributors name like this, but you have to label the issue as "medium", because i have to take every ones' profile link and profile pictures.
![image](https://user-images.githubusercontent.com/66861659/110202707-7cda3e00-7e90-11eb-9fab-41682d3d61cf.png)

**Comment by yashlikescode** [comment]
Otherwise, I will add the image provided by you as you told me,
your choice
tell me what you think

**Comment by Harshal0902** [comment]
It will be better if you go like this way:
https://contributors-img.web.app/image?repo=Harshal0902/Rudra

Because the README will become very long.
