### ISSUE TITLE
Dynamic Favicon

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#44]
Design and make a dynamic favicon for Dark mode and light modes. You can refer these:
- [GeeksforGeeks](https://www.geeksforgeeks.org/how-to-change-favicon-dynamically/)
- [Medium Blog](https://medium.com/@alperen.talaslioglu/building-dynamic-favicon-with-javascript-223ad7999661)

**Comment by Rajdeep-99** [comment]
Sir can I work on this project?

**Comment by Harshal0902** [comment]
@Rajdeep-99 if you are a participant of LGM Summer of Codes, it would be better if you start working on this issue when the event starts.

**Comment by Harshal0902** [comment]
@Rajdeep-99 I am assigning this issue to you

**Comment by Rajdeep-99** [comment]
Thank you
