### ISSUE TITLE
Write a Guide for Deploying the App to Docker

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#45]
* Please name it `Docker.MD`
 * Make and place it inside the `Guides/` directory of the master branch
 * Add Snapshots of the process as and where required
 * Add `Useful Tips` section for certain optimizations, bug fixing advice, and site corresponding references

**Comment by mohit200008** [comment]
CAN I WORK ON THIS ?

**Comment by Harshal0902** [comment]
@mohit200008 go ahead. You can work on this issue.

**Comment by Astitva7717** [comment]
please assign me this task (if you thinks it will enhance your project) under the Lgm-Soc'21 and add labels if possible.

**Comment by Harshal0902** [comment]
@Astitva7717 the issue is already assigned to someone else, so you are requested to go for other issues.
