### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#46]
Build and implement a 404 Page Not Found.

**Comment by patelaryan7751** [comment]
hello @Harshal0902 may i work on this issue?

**Comment by Harshal0902** [comment]
@patelaryan7751 go ahead

**Comment by Harshal0902** [comment]
@patelaryan7751 the Season of Codes will start from 10 June and if you are a participant of SOC, I will suggest not to work on this until the events start.

**Comment by ajaydr16** [comment]
Hello @Harshal0902 ,
Can I work on this as a part of LGMSOC21?

**Comment by ajaydr16** [comment]
For this issue, a 404 page should be designed or even add 404.html as redirection to all wrong links?

**Comment by Harshal0902** [comment]
@ajaydr16 for this issue, a 404 page should be designed and it should be redirected to the home page. Right now the issue is assigned to someone else, so you are requested to go for other issues.

**Comment by patelaryan7751** [comment]
@Harshal0902 you can check the above said changes [here](https://github.com/Harshal0902/Rudra/pull/62)
