### ISSUE TITLE
Add Rudra logo in title bar

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [Harshal0902/Rudra#48]
<img align="center" alt="Coding" width="100%" height="300" src="https://i.postimg.cc/9Fhnssyk/title-icon.png](https://postimg.cc/F1TpLWWb">

**Comment by QAZIMAAZARSHAD** [comment]
Hi, 
@Harshal0902  can you please assign me this issue.

**Comment by Harshal0902** [comment]
@QAZIMAAZARSHAD the site already has a favicon. So, you can go with another issues.
