### ISSUE TITLE
Design an AboutUs

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#49]
Design an about us page

**Comment by aum-singhal** [comment]
Hello sir. I can try on this page.
Can you please provide the details you want to show in the about us page.
And if possible, then can you also assign this to me. My contribution will be from Let'sGrowMore Open Source.

Thanks

**Comment by Harshal0902** [comment]
@aum-singhal the Season of Codes will start from 10 June, so it's better that I assign this issue to you when the event starts.

**Comment by aum-singhal** [comment]
okay sure. till the time can you tell me what all you need to show on the about us page ? so that i can work on the template 😅

**Comment by Harshal0902** [comment]
You can design it in whatever way you want, but you have to *design* it for responsive mode as well, you don't need to build it

**Comment by milan-mohapatra** [comment]
can i try it
...is it count on soc?

**Comment by Harshal0902** [comment]
@TheGrayGodfather it will not count as SOC haven't started yet

**Comment by Swarnava77** [comment]
Hello, can I contribute in this?

**Comment by Harshal0902** [comment]
@Swarnava77 the Season of Codes will start from 10 June, so it's better that I assign this issue to you when the event starts.

**Comment by Harshal0902** [comment]
@aum-singhal I am assigning this issue to you. @greenblade29 and @Swarnava77 you can try other issues.

**Comment by aum-singhal** [comment]
Thanks a lot sir. I will get to my work right now.
Thanks again for the opportunity 😊

**Comment by aum-singhal** [comment]
hello sir.
I have almost completed my work but i was wondering when to push it and should i push it on the main branch or should I create my own branch and then push the code in that branch?

Can you please help me with these 2 things 😅
Thanks 😊

**Comment by Harshal0902** [comment]
Push it in the main branch, and it's up to you whether you want to create a branch or not, but do a PR after 10th.

**Comment by aum-singhal** [comment]
Okay then 👍
I will make the PR tomorrow. 
Thanks for the help 😊

**Comment by aum-singhal** [comment]
Hello Sir.

I have created the PR. Please let me know if any changes are needed 🙂
