### ISSUE TITLE
SVG Animation for Toggle Button

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#51]
Replace the Dark-Mode button with a dark mode toggle.

[Reference](https://codepen.io/bnthor/pen/WQBNxO)

**Comment by SamikshaSankar** [comment]
When we toggle the dark mode will be converted into light mode just like that you want to add? @Harshal0902

**Comment by SamikshaSankar** [comment]
I work on this issue under LGM-SOC'21 participant..please assigned me @Harshal0902

**Comment by Harshal0902** [comment]
@SamikshaSankar go ahead, you just need to replace the Dark-Mode button with a dark mode toggle. The site already has a dark mode.

**Comment by RituCs** [comment]
I would like to work on this issue if @SamikshaSankar  is not working.

**Comment by SamikshaSankar** [comment]
@RituCs I am working on this issue
