### ISSUE TITLE
Update style of cards

### ISSUE THREAD

**Issue by SamikshaSankar** [Harshal0902/Rudra#52]
## Is your feature request related to a problem? Please describe.
The content on cards its not show proper.

## Describe the solution you'd like
I want to like flip box and adding zoom hover effect. The content will we shown in backward side by using hover effect.

I work on this issue under LGM-SOC'21 participant..please assigned me @Harshal0902 

![rudra](https://user-images.githubusercontent.com/52104082/121180798-de8ab980-c87e-11eb-8931-ede5b2990d0b.jpg)

**Comment by Srit20** [comment]
I would like to work on this issue under LGMSOC'21 participant. Please assign me @Harshal0902 if she can't do

**Comment by SamikshaSankar** [comment]
@Srit20 I am working on this
