### ISSUE TITLE
Resturcture English version.

### ISSUE THREAD

**Issue by Ashuto7h** [Harshal0902/Rudra#56]
## Describe the Issue
Restructure the English version of the project as a single React app.
The code of this application is quite messy with a lot of HTML files and React components. 
It's hard to find links between them and debug. 

I suggest making a React-level project structure for the English version of this application.
The React project will be kept in a new directory until it gets completed. after which we will remove the old directory.

Let's check what others says about this issue. 
If you like the issue, give a thumbs up

**Comment by Ashuto7h** [comment]
👍🏼

**Comment by Harshal0902** [comment]
@Ashuto7h Yes we can do that. So which page/section would you like to work on?

**Comment by Ashuto7h** [comment]
I will start from English > public

**Comment by Harshal0902** [comment]
So you want to build a whole public section or some specific pages of the public section?

**Comment by Ashuto7h** [comment]
will try with whole, and narrow down to my capabilities after that.
