### ISSUE TITLE
Extra gap after footer in English-home.html and Kannada-home.html

### ISSUE THREAD

**Issue by ajaydr16** [Harshal0902/Rudra#57]
## Describe the bug
There is a small gap in both the HTML files of English and Kannada.

![bug](https://user-images.githubusercontent.com/55269615/121568329-38d17900-ca3d-11eb-9c86-31367192afde.jpg)

If you can assign (for LGMSOC) this to it would be done with very minimal steps.

## To Resolve
Steps to resolve the behaviour:
1.  go to rootDirectory>English>home.css
2.  change the margin which is presently assigned as for the complete page to only for the top of page
3.  go to rootDirectory>Kannada>home.css
4.  change the margin which is presently assigned as for the complete page to only for the top of page

**Comment by Harshal0902** [comment]
@ajaydr16 go for it.
