### ISSUE TITLE
Home Page: Whole article is not clickable 

### ISSUE THREAD

**Issue by ajaydr16** [Harshal0902/Rudra#59]
## Describe the solution you'd like
On the home page (i.e landing page) the cards or options mention English, Kannada, Other Languages those can only be clickable only when they click on the blue-coloured text i.e "click here".

![bug2](https://user-images.githubusercontent.com/55269615/121583675-2f9cd800-ca4e-11eb-88c6-1dbf2031e758.jpg)

But as taking in the perspective of a user. He/She doesn't locate that click here much. They might just click on that card but it will not get redirected. 

If you assign this to me (under LGMSOC) I can add this feature to more user friendly.

**Comment by Harshal0902** [comment]
@ajaydr16 go for it.
