### ISSUE TITLE
Copyright year will update itself

### ISSUE THREAD

**Issue by ghost** [Harshal0902/Rudra#72]
## Is your feature request related to a problem? Please describe.
The current Problem is that the copyright year in the footer needs manual upgradation every time.

## Describe the solution you'd like
I can solve this problem by adding the script so that the year in the copyright will update itself every time and no longer needs manual upgradation.

## Additional context
Please assign this issue to me and add labels to it . I want to contribute in this project under LGMSOC21.

**Comment by Harshal0902** [comment]
@Kritika-2000 go for it

**Comment by ghost** [comment]
@Harshal0902 Thank you✌
