### ISSUE TITLE
Add Let'sGrowMore logo under 'This Project is a part of the following Open Source Program' section

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [Harshal0902/Rudra#75]
##  description.
Since this project is also the part of LGMSOC'21 . It should also be stated in 'This Project is a part of the following Open Source Program' section in README.md .

## solution
I will like to add LGMSOC logo in the section .

**Comment by Harshal0902** [comment]
@Rishabhraghwendra18 go for it
