### ISSUE TITLE
Wrong use of Syntax in README.md section

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [Harshal0902/Rudra#78]
## Description
Under `This Project is a part of the following Open Source Program` section in README.md . In place of alt text in markdown syntax , we have `<img/>` tag . Take a look:
`[<img src ="https://github.com/Ayush7614/Rudra/blob/main/cwoc.png" alt ="Cross Winter of Code"></img>](https://crosswoc.ieeedtu.in/)`

It's also  negatively effecting SEO .

I want to replace image tag with  `Cross Winter of Code` . Take a look:
`![Cross Winter of Code](https://crosswoc.ieeedtu.in/)`

I will really like to work on this issue under LGMSOC

**Comment by Harshal0902** [comment]
@Rishabhraghwendra18 got for it

**Comment by Harshal0902** [comment]
@Rishabhraghwendra18 The image of CrossWoC is not there in README.md kindly add it

**Comment by Rishabhraghwendra18** [comment]
> @Rishabhraghwendra18 The image of CrossWoC is not there in README.md kindly add it

Sorry I didn't see that . I have made a fresh PR . Please check whether it's now working or not.
