### ISSUE TITLE
Minor errors

### ISSUE THREAD

**Issue by varunwho** [Harshal0902/Rudra#85]
### The text is not clearly visible since both are having a light color
![Screenshot 2021-06-17 092919](https://user-images.githubusercontent.com/53107832/122330262-7dcf4100-cf50-11eb-886c-27deee1da4dc.png)

### A color like this matches with the navbar colors and the text is also visible in this color
![Screenshot 2021-06-17 094244](https://user-images.githubusercontent.com/53107832/122330265-7f006e00-cf50-11eb-9f0b-c8a9511a9fd8.png)

### **The form isn't exactly on the center and also a border could be added around the description box**
![Screenshot 2021-06-17 094301](https://user-images.githubusercontent.com/53107832/122330267-7f990480-cf50-11eb-8337-c46452ffc58b.png)

And also the scroll bar colour could be changed to default colors as it is looking a bit flashy (Upto you, if you want I can change it or else it's okay)

And also personally I felt that the polygon footer isn't looking that great, instead the simple footer would look better I feel.
Also the navbar could be made better, I'll try to show you some samples if you want the navbar styling to be changed

**Comment by Harshal0902** [comment]
@varunwho go for it. You can change the footer and scroll bar
