### ISSUE TITLE
Design and add favicon to the webpage

### ISSUE THREAD

**Issue by Harshal0902** [Harshal0902/Rudra#9]
Design a Favicon for the site and add it to all webpages

**Comment by greenblade29** [comment]
I can work on this issue. Can you please assign it to me?

**Comment by Hritikkumar** [comment]
Hi Sir, I would like to contribute to this project. Kindly assign it to me

**Comment by Harshal0902** [comment]
@greenblade29 you can work on this issue. You are requested to join the Discord server using this [link](https://discord.gg/qxgsn99W). Try to complete it within 3 days and follow the CONTRIBUTION.md for making PR.
