### ISSUE TITLE
Add score table of LGMSOC in read me

### ISSUE THREAD

**Issue by nisha331** [Harshal0902/Rudra#93]
## Is your feature request related to a problem? Please describe.
I want to add this in read me kindly assign it to me
![1](https://user-images.githubusercontent.com/76838660/122599904-b07e5400-d08c-11eb-96c1-2f7de45ef0b9.PNG)
.

**Comment by Harshal0902** [comment]
@nisha331 I am supposed to make this Points table, along with the points given to contributors.
