### ISSUE TITLE
Add a Feedback page

### ISSUE THREAD

**Issue by ishitakapoor26** [Harshal0902/Rudra#97]
Add a Feedback page

**Comment by ishitakapoor26** [comment]
@Harshal0902 pls assign me this issue.

**Comment by Harshal0902** [comment]
@ishitakapoor26 go for it

**Comment by Srit20** [comment]
I would like to work on this issue under LGMSOC'21 participant. Please assign me @Harshal0902

**Comment by ishitakapoor26** [comment]
@Srit20 I am already working on it and its almost done.

**Comment by Srit20** [comment]
@ishitakapoor26 ok carry on all the best

**Comment by ishitakapoor26** [comment]
@Harshal0902 pls review pr.
