### ISSUE TITLE
Design logo for website

### ISSUE THREAD

**Issue by ishitakapoor26** [Harshal0902/Rudra#98]
Design logo for website

**Comment by ishitakapoor26** [comment]
@Harshal0902 pls assign me this issue.

**Comment by Harshal0902** [comment]
@ishitakapoor26 go for it

**Comment by ishitakapoor26** [comment]
@harshal pls checkout designs...

![GitMarkonics (4)](https://user-images.githubusercontent.com/78542333/122900023-f75c9a00-d369-11eb-83f2-306fc785df74.png)

**Comment by ishitakapoor26** [comment]
![GitMarkonics (5)](https://user-images.githubusercontent.com/78542333/122900093-03e0f280-d36a-11eb-9453-ad2edbc2a31b.png)

**Comment by ishitakapoor26** [comment]
![GitMarkonics (6)](https://user-images.githubusercontent.com/78542333/122901926-a6e63c00-d36b-11eb-8e73-4c3e29b6a97e.png)

**Comment by Harshal0902** [comment]
The 1st one looks good. Go with that one

**Comment by ishitakapoor26** [comment]
> The 1st one looks good. Go with that one

@Harshal0902 okay in which directory I have to place it?

**Comment by Harshal0902** [comment]
Put it under assets folder
