### ISSUE TITLE
add some badges to README.md

### ISSUE THREAD

**Issue by Umesh-01** [Harshal0902/Rudra#99]
## Is your feature request related to a problem? Please describe.
add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/83420185/122667586-2c81b480-d1d1-11eb-9d77-24487d7581b1.png)

I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

### Work under/as

- [x] LGMSOC
- [ ] Contributor

**Comment by Harshal0902** [comment]
@Umesh-01 go for it
